TreeView/Controllers/TreeviewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web;
using System.Web.Mvc;
using Ubiety.Dns.Core;

namespace TreeView.Controllers
{
    public class TreeviewController : Controller
    {
        // GET: Treeview
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Simple()
        {
            List<Menu> all = new List<Menu>();
            using(MyDataEntities dc= new MyDataEntities())
            {
                //all = dc.Menu.OrderBy(a => a.ParentMenuID).ToList();
                all = dc.Menu.Where(a => a.ParentMenuID.Equals(0)).ToList();
            }
            return View(all);
        }
        public JsonResult Getsubmenu(string pid)
        {
            List<Menu> submenu = new List<Menu>();
            int pID = 0;
            int.TryParse(pid, out pID);
            using (MyDataEntities dc = new MyDataEntities())
            {
                submenu = dc.Menu.Where(a => a.ParentMenuID.Equals(pID)).OrderBy(a => a.MenuName).ToList();
            }
            return new JsonResult { Data = submenu, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public void Export()
        {
            using (MyDataEntities db = new MyDataEntities())
            {
                StringWriter client = new StringWriter();
                client.WriteLine("\"MenuID\",\"MenuName\",\"NaveURL\",\"ParentMenuID\"");
                Response.ClearContent();
                Response.AddHeader("content-disposition", string.Format("attachement;filename=TreeviewMenu{0}.txt", DateTime.Now));
                Response.ContentType = "text/txt";
                Response.ApplyAppPathModifier("D:/");
                var listMenu = db.Menu.OrderBy(x => x.MenuId);
                foreach (var news in listMenu)
                {
                    client.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\"",
                        news.MenuId, news.MenuName, news.NaveURL, news.ParentMenuID));
                }
                Response.Write(client.ToString());
                Response.End();
            }

        }
    }
    

}

TreeView/Views/Treeview/Simple.cshtml
@model List<TreeView.Menu>
@{
    ViewBag.Title = "Simple";
}
<style>

    .loadingP {
        background-image: url('../Images/ui-icons_454545_256x240.png');
        width: 15px;
        display: inline-block;
    }

    .collapse {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .expand {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .treeview ul {
        font: 14px Arial,Sans-Serif;
        margin: 0px;
        padding-left: 20px;
        list-style: none;
    }

    .treeview > li > a {
        font-weight: bold;
    }

    .treeview li a {
        padding: 4px;
        font-size: 12px;
        display: inline-block;
        text-decoration: none;
        width: auto;
    }
</style>
<h2>Treeview from database</h2>
<div style="border: 1px solid black; padding:10px; background-color:#FAFAFA">
    <div class="treeview">
        @{
            if (Model != null && Model.Count() > 0)
            {
                <ul>
                    @foreach (var i in Model)
                    {
                        <li>
                            <span class="collapse collapsing" data-loaded="false" pid="@i.MenuId">&nbsp; </span>
                            <span>
                                <a href="@i.NaveURL">@i.MenuName</a>
                            </span>
                        </li>
                    }

                   
                </ul>
            }
        }

    </div>
</div>
@using (Html.BeginForm("Export", "Treeview", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="submit" value="Export" />
}

@section Scripts{
    <script src="~/Scripts/MyTreeview.js"></script>
   }